version: '3'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/web/Dockerfile
  #   depends_on:
  #     - app
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - asset-volume:/etc/nginx/html/
  db:
    image: postgres:10.2-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
    ports:
      - "5431:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: >
      ash -c "bundle exec rake db:migrate
      && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - asset-volume:/app/public
    env_file:
      - ./.env
    environment:
      - RAILS_ENV=production
volumes:
  asset-volume:
