version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=staging.acbw.me
    networks:
      - nginx_proxy_stratas
    ports:
      - "80:80"
    restart: always
    volumes:
      - asset-volume:/etc/nginx/html/
  db:
    image: postgres:10.2-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - nginx_proxy_stratas
    ports:
      - "5431:5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    command: >
      ash -c "bundle exec rake db:migrate
      && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - asset-volume:/app/public
    networks:
      - nginx_proxy_stratas
    env_file:
      - ./.env
    environment:
      - RAILS_ENV=production
volumes:
  asset-volume:

networks:
  nginx_proxy_stratas:
    external: true
